/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.codemodder.sample;

import io.codemodder.Runner;

import java.util.List;

/** Run the codemod. */
public final class App {

    public static void main(final String[] args) {
        // invoke the codemod runner
        Runner.run(
            List.of(AddMissingValidAssertionsToJerseyCodemod.class, UseJerseyDTOWhenPossibleCodemod.class),
            args
        );
    }
}
